justdo:
  uploadPath: resource/uploaded_files/
  logfilesPath: applog/
logging:
  level:
    root: INFO
    com.justdo: DEBUG
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/justdo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    jackson:
           #参数意义：
           #JsonInclude.Include.ALWAYS              默认
           #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
           #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
           #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
            default-property-inclusion: ALWAYS
            time-zone: GMT+8
            date-format: yyyy-MM-dd HH:mm:ss
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
      host: 127.0.0.1
      #端口
      port: 6379
      #密码
      password: oxhide
      # 连接超时时间（毫秒）
      timeout: 0

      expire: 1860
      pool:
         #连接池最大连接数 设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
         max-active: 5000
         #连接池中的最小空闲连接
         min-Idle: 300
         #连接池中的最大空闲连接
         max-Idle: 500
         #连接池最大阻塞等待时间（使用负值表示没有限制）
         max-Wait: 6000
         #连接池的最大数据库连接数。
         #maxActive: 600
         #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
         maxTotal: 1000
         #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
         maxWaitMillis: 1000
         #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
         testOnBorrow: true
         #
         testOnReturn: true
         #在空闲时检查有效性, 默认false
         testWhileIdle: true
         #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
         timeBetweenEvictionRunsMillis: 6000
         #连接的最小空闲时间 默认1800000毫秒(30分钟)
         minEvictableIdleTimeMillis: 300000
         #每次释放连接的最大数目,默认3
         numTestsPerEvictionRun: 1024
  jackson:
      #参数意义：
      #JsonInclude.Include.ALWAYS              默认
      #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
      #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
      #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
     default-property-inclusion: ALWAYS
     time-zone: GMT+8
     date-format: yyyy-MM-dd HH:mm:ss

