#使用外部Tomcat部署访问的时候，application.properties(或者application.yml)中配置的
#server.port=
#server.servlet.context-path=
#将失效，请使用tomcat的端口，tomcat，webapps下项目名进行访问。
server:
  session-timeout: 1800
  connection-timeout: 300000
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8088
  #spring boot 项目中，application.properties增加如下配置指定tomcat的基目录，否则spring boot内嵌的tomcat容器会创建一个临时目录，但是此目录有一个定期清除策略，会影响web容器资源的使用，所以指定在项目根目录创建目录
#  ssl:
#     key-store: classpath:www.qchen.xyz.jks
#     key-store-type: JKS
#     #密钥库密码
#     key-store-password: i63ym1a221oxx
  tomcat:
     basedir: ./deployer/tomcat
#  servlet.context-path: jsutdo
# uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  http:
    multipart:
    #单个文件的大小
      max-file-size: 100Mb
    #整体文件的大小
      max-request-size: 200Mb
  devtools:
    restart:
      enabled: true
     # exclude:
     # trigger-file:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
mybatis:
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.justdo.**.domain
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: redis




























